#ifndef _SERIAL_DEFINITIONS_
#define _SERIAL_DEFINITIONS_

enum {
    SERIAL_PRINT_NOTHING = 0x10,
    SERIAL_PRINT_MAG_RAW = 0x11,
    SERIAL_PRINT_MAG_CALIB = 0x12,
    SERIAL_PRINT_ACC_RAW = 0x13,
    SERIAL_PRINT_ACC_CALIB = 0x14,
    SERIAL_PRINT_GYRO_RAW = 0x15,
    SERIAL_PRINT_GYRO_CALIB = 0x16,
    SERIAL_PRINT_AHRS = 0x20,

    SERIAL_MAG_SET_OFFSET = 0x30,
    SERIAL_MAG_GET_OFFSET = 0x31,
    SERIAL_MAG_SET_GAIN = 0x32,
    SERIAL_MAG_GET_GAIN = 0x33,
    SERIAL_ACC_SET_OFFSET = 0x40,
    SERIAL_ACC_GET_OFFSET = 0x41,
    SERIAL_ACC_SET_GAIN = 0x42,
    SERIAL_ACC_GET_GAIN = 0x43,
    SERIAL_GYRO_SET_OFFSET = 0x50,
    SERIAL_GYRO_GET_OFFSET = 0x51,
    SERIAL_GYRO_SET_GAIN = 0x52,
    SERIAL_GYRO_GET_GAIN = 0x53,

    SERIAL_BAUDRATE = 57600,
    SERIAL_READ_BUFFER_SIZE = 65,
} ;

#endif
