#ifndef _SERIAL_DEFINITIONS_
#define _SERIAL_DEFINITIONS_

#include <string>

// TODO: Why are some constants as string and others as enum/int?

const std::string SERIAL_HANDSHAKE = "0x05";
const std::string SERIAL_DONE = "0x06";

enum {
  SERIAL_PRINT_NOTHING = 0x10,
  SERIAL_PRINT_MAG_RAW = 0x11,
  SERIAL_PRINT_MAG_CALIB = 0x12,
  SERIAL_PRINT_ACC_RAW = 0x13,
  SERIAL_PRINT_ACC_CALIB = 0x14,
  SERIAL_PRINT_GYRO_RAW = 0x15,
  SERIAL_PRINT_GYRO_CALIB = 0x16,
  SERIAL_PRINT_AHRS = 0x20,

  SERIAL_MAG_SET_CALIB = 0x30,
  SERIAL_MAG_GET_CALIB = 0x31,
  SERIAL_ACC_SET_CALIB = 0x40,
  SERIAL_ACC_GET_CALIB = 0x41,
  SERIAL_GYRO_SET_CALIB = 0x50,
  SERIAL_GYRO_GET_CALIB = 0x51,

  SERIAL_RESET_FACTORY_DEFAULTS = 0x60,
  SERIAL_RESET_KVSTORE = 0x70,

  SERIAL_BAUDRATE = 57600,
  SERIAL_READ_BUFFER_SIZE = 1024,
};

#endif
